# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-06 05:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20171005_2203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='losts',
            new_name='loses',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='tie',
            new_name='ties',
        ),
    ]
